### ISSUE TITLE
Ajustar tela de Inicio e criar evento de click para o botao de registrar.

### ISSUE THREAD

**Issue by jparrigo** [Guilherme-Jorge/DenTeeth#10]

**Comment by jparrigo** [comment]
#11

**Comment by Guilherme-Jorge** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Profissional] Fazer tela de início - Sprint 1](https://trello.com/c/thNuMPFm/5-profissional-fazer-tela-de-in%C3%ADcio-sprint-1)
