### ISSUE TITLE
Criar o layout da activity da camera

### ISSUE THREAD

**Issue by jparrigo** [Guilherme-Jorge/DenTeeth#13]

**Comment by Guilherme-Jorge** [comment]
#21

**Comment by Guilherme-Jorge** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Cliente] Fazer layout da tela de câmera para foto de perfil - Sprint 1](https://trello.com/c/vEb4WAAm/16-cliente-fazer-layout-da-tela-de-c%C3%A2mera-para-foto-de-perfil-sprint-1)
