### ISSUE TITLE
Implementação do Firebase no registro do Profissional

### ISSUE THREAD

**Issue by jparrigo** [Guilherme-Jorge/DenTeeth#17]

**Comment by Guilherme-Jorge** [comment]
#20

**Comment by Guilherme-Jorge** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Profissional] Fazer processo de criar conta - Sprint 1](https://trello.com/c/pZv15oqo/2-profissional-fazer-processo-de-criar-conta-sprint-1)
