### ISSUE TITLE
Adição da Progress Bar as telas de Registro e Termos de Uso

### ISSUE THREAD

**Issue by jparrigo** [Guilherme-Jorge/DenTeeth#18]

**Comment by jparrigo** [comment]
#19

**Comment by Guilherme-Jorge** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Profissional] Fazer processo de criar conta - Sprint 1](https://trello.com/c/pZv15oqo/2-profissional-fazer-processo-de-criar-conta-sprint-1)
