### ISSUE TITLE
Alterar a criação de conta para uma activity com fragments

### ISSUE THREAD

**Issue by Guilherme-Jorge** [Guilherme-Jorge/DenTeeth#26]
Mudar o RegistroActivity, TelaCameraActivity e o TermosDeUsoActivity para RegistroFragment, TelaCameraFragment e TermosDeUsoFragment, além de criar CriarContaActivity e conectar tudo

**Comment by Guilherme-Jorge** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Profissional] Substituir as Activities de Criar Conta por um conjunto de Fragments - Sprint 2](https://trello.com/c/14IKXW5E/35-profissional-substituir-as-activities-de-criar-conta-por-um-conjunto-de-fragments-sprint-2)

**Comment by jparrigo** [comment]
#33
