### ISSUE TITLE
Criar tela de resposta à emergência

### ISSUE THREAD

**Issue by Guilherme-Jorge** [Guilherme-Jorge/DenTeeth#28]
Tela terá as fotos da emergência, o motivo e 2 botões, um para negar chamado e outro para aceitar chamado.

**Comment by Guilherme-Jorge** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Profissional] Fazer telas de recebimento de emergência - Sprint 2](https://trello.com/c/fO4R37Vt/14-profissional-fazer-telas-de-recebimento-de-emerg%C3%AAncia-sprint-2)

**Comment by jparrigo** [comment]
#33
